### ISSUE TITLE
close/prev/next icon problem

### ISSUE THREAD

**Issue by pcarpo** [pupunzi/jquery.mb.gallery#2]
hi there 

(i'm a novice)

i'm trying to emulate the demo 'jQuery mb.thumbGrid Plugin Demo'
taken from http://www.jqueryscript.net/gallery/Stylish-jQuery-Gallery-Grid-with-Lightbox-Support-mb-thumbGrid.html
(not than the thumb gallery demo 1/2 examples)
I don't want the preview images to scale like the one you can download does

So i saved the demo and fiddled around with the folder structure
it works perfectly except for the lightbox icons (for close / next / prev) which aren't displaying when you click through from preview image. 
have i got the font/icon folder in the right place?

any suggestions?

i've invested a lot of time getting it to work and so much of it works brilliantly i'd hate to have to give up now

**Comment by pupunzi** [comment]
Hi,
The font folder should be on the same level of the CSS file. If you want to place it somewhere else you need to change the @font-face path.

Hope this helps you

**Comment by pcarpo** [comment]
thanks for your help - 
thats where i got them....

where is the @font-face path meant to be?

<img width="1031" alt="screen shot 2017-02-05 at 21 13 32" src="https://cloud.githubusercontent.com/assets/25570994/22629986/29a85318-ebe9-11e6-84a2-256c3017411a.png">

this is what i see

**Comment by pcarpo** [comment]
i fixed it  - thanks for your help
